project:
  type: website

website:
  title: "Simple_Quarto_Website"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.ipynb
      - href: slides/slides.ipynb
        text: Presentation

bibliography: reference.bib
format:
  html:
    theme: cosmo
    toc: true

 
    